### ISSUE TITLE
Improved deployment schedule proposal

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#1102] opened 2019-04-29 12:14 UTC
## What Needs to be Documented?
At the moment, deployment gets triggered when a merge is made to master.
This build includes also non-docs (eg client, ios, android...) repos.

**Problem:**
If there is a backport or a change in the other repos, these only get deployed when triggered via any docs master merge, not necessarily related the the docs master merge.

**Proposal:**
Have a nightly job that checks any merges made to other doc branches or the other repos post the last deployment, one positive match is enough to trigger a deployment.

**Benefit:**
We have the guarantee, that non docs master changes get deployed at least once a day.

@tboerger @settermjd

**Comment by tboerger** [comment] 2019-04-29 18:35
That won't get in before we updated Drone to >= 1.1.0

**Comment by voroyam** [comment] 2019-08-29 14:36
Did we upgrade already? @tboerger

**Comment by tboerger** [comment] 2019-10-18 10:07
We are already running a more current version, but the behavior won't be changed to nightly builds, but to triggered builds when i can get to it.

**Comment by settermjd** [comment] 2019-10-18 11:11
> We are already running a more current version, but the behavior won't be changed to nightly builds, but to triggered builds when i can get to it.

thank you for the feedback.

**Comment by mmattel** [comment] 2019-10-18 18:00
I cant help here. I just highlighted the issue but have limited knowledge how this can be achieved. Someone with proper background knowledge is necessary. Removing my assignment therefore.

**Comment by settermjd** [comment] 2020-01-31 13:41
> We are already running a more current version, but the behavior won't be changed to nightly builds, but to triggered builds when i can get to it.

Have you been able to make further progress on this, @tboerger?

**Comment by settermjd** [comment] 2020-03-03 09:43
@xoxys, can you help out with this issue?

**Comment by xoxys** [comment] 2020-04-23 06:39
Thanks for your input @settermjd AFAIK there are two possible solutions:
- simply add a nightly job which will just run the last successful run for the master branch
- add drone downstream trigger to the client repos and trigger a owncloud/docs ci run

**Comment by voroyam** [comment] 2021-03-02 10:31
daily job active. closing

**Comment by mmattel** [comment] 2021-03-02 11:19
@voroyam can you confirm that when there is a merge to a branch (not master but eg 10.6), a nightly job will publish the change? ATM, as far I see, publishing only happens when a merge to master is made.

**Comment by voroyam** [comment] 2021-03-02 11:25
I talked to @xoxys about the first of his proposals, and he pointed out that it was already implemented, for me this means that the issue is fixed.

If you tell me how I would to confirm this - I will try.

**Comment by xoxys** [comment] 2021-03-02 11:55
@mmattel What do you try to achieve? 

1. Publishing changes on the backport branches (10.6, 10.5)
Correct, right now only the PDF is getting uploaded on every backport branch change. Why it was done this way, I don't know. This behavior is congtrolled by the `deployment_branch` setting in the drone starlark config file which is a single string `deployment_branch = master` right now. But this could be changed to a list, to trigger a full deployment on multiple branches e.g. `deployment_branches = ['master', '10.6', '10.5']`. It is also correct that we have just a single nightly drone job which re-runs the last successful job of the master branch. As an alternative to the `deployment_branch` restructuring we could add other drone jobs to trigger nighties from other branches.
2. Publishing changes related to an external repo e.g. client docs. 
This is currently solved by the drone nightly job as the branch doesn't matter for external repos.

**Comment by xoxys** [comment] 2021-03-02 12:03
I was a bit wrong with 1) this is handled in https://github.com/owncloud/docs/blob/10.6/.drone.star and doesn't really make sense IMO... https://github.com/owncloud/docs/blob/10.6/.drone.star#L7-L16 is defining "master" as deployment branch (which will never be true on backport branches) while "upload-pdf" is using another control variable than "upload-html".... https://github.com/owncloud/docs/blob/10.6/.drone.star#L155

**Comment by mmattel** [comment] 2021-03-02 12:05
> What do you try to achieve?

ad 1. It is exactly what you desribe in your comment. Atm, a publish of docs is based if a merge is made on master only. But imagine that there is a merged backport to whatever branch only. This get´s only published when again a PR to master gets merged. This is a very bad situation, because what if this backport is important and there is no upcoming master merge?
We have to get out of that situation that you have a merge to a branch not being master not being published.
One idea was to setup a nightly job to see if there are non published non master merges and then do a publishing run.
As far I remember, which for sure needs a reevaluation, to not "overoad/confuse" drone as there are more branch merges than master merges...
I am open for any discussion about, maybe you ping me on talk to clarify that offline and further present a result here.

**Comment by xoxys** [comment] 2021-03-02 14:01
As discussed with @mmattel by call: Find a way to publish on all supported version branches, right now: "master", "10.6" and "10.5". I'll review the current setup and prepare a possible fix.

**Comment by xoxys** [comment] 2021-03-10 07:24
Had a closer look, and it seems all issues were already fixed:

- Client docs are updated once a day by the nightly drone job
- Backports to one of the version branches will trigger a master branch build as the last step (and the master branch itself will publish all versions defined in site.yml)

If I don't miss something else we can close this issue again.

**Comment by mmattel** [comment] 2021-03-10 07:34
This is great news, first time it is described how the setup is currently made.

I will add a note to readme.me to have this published and as a general reminder to us all.
(And I will do a test with a branch 😄 )

**Closed** 2021-03-15 11:48 UTC
Labels: deployment, enhancement, p4-low, question, work in progress
