### ISSUE TITLE
THP needed in docs? 

### ISSUE THREAD

**Issue by JKawohl** [owncloud/docs#2555] opened 2020-04-09 08:35 UTC
https://github.com/owncloud/docs/pull/1597

@mmattel 

I just stumbled over THP in  above mentioned pull request and i am wondering if this is an absolute hard requirement for anything. As this has a broader impact i would rather not have it in our docs. But rather point to mariadb doc pages.

**Comment by jnweiger** [comment] 2020-04-09 09:11
The docs at https://doc.owncloud.com/server/10.4/admin_manual/installation/server_prep_ubuntu_18.04.html#disable-transparent-huge-pages-thp have instructions to *disable* THP and hints at interactions of  MariaDB and Redis. I'd be curious to learn more about the background. Are there errors or warnings from redis, when THP remains at typical default settings?

**Comment by mmattel** [comment] 2020-04-09 09:50
It is all about a matter of perfomance panalty having THP enabled using databased.

**Please see:**

https://redis.io/topics/latency#latency-induced-by-transparent-huge-pages
`Unfortunately when a Linux kernel has transparent huge pages enabled, Redis incurs to a big latency penalty after the fork call is used in order to persist on disk. Huge pages are the cause of the following issue: ...`

https://stackoverflow.com/questions/48743100/why-thp-transparent-huge-pages-are-not-recommended-for-databases-like-oracle-a
`Apparently it's because THP are swappable, and the Linux swap subsystem can only handle base page sizes and not HugePages. This creates a race condition which has a significant impact on system performance.`

https://unix.stackexchange.com/questions/196737/is-thp-good-or-bad-for-mysql-server
`It's good for everyone to remember that huge pages and transparent huge pages are not the same issue. Yes, huge pages are good for databases when they're designed to use them. Transparent huge pages make normal memory access into huge page memory access which can cause excessive I/O for a database that was expecting to use regular sized pages. In general for a dedicated database server, leave huge pages settings and disable just the transparent huge pages`

Hope this gives you a better insight about why disabling THP is a good thing.

@JKawohl disagree about just pointing to MariaDB / MySQL, (Oracle, Postgres), Redis. Make it easy for an admin to disable it, you avoid performance panalties. The procedure described is very compact and well working.

**Comment by jnweiger** [comment] 2020-04-09 11:30
Thany you Martin, for the details. 

I had seen the discussion of swappable THP pages, and dismissed that as "so what, if it needs to swap, performance is ruined anyway" 

But now the key insight for me is `Transparent huge pages make normal memory access into huge page memory access which can cause excessive I/O for a database that was expecting to use regular sized pages`

Regarding the docs, I first would suggest 
* Clearly label that as "performance tuning" or move it to a tuning section. (See below...)
* Add a rationale, including 
  - the above insight and/or pointers to
  - redis and mariadb discussion (https://redis.io/topics/latency, ...)
* Point out, when running redis and mariadb on different machines, *where* to check THP.

But second, maybe a deeper review is due now:

There is a nice discussion of the topic on https://www.percona.com/blog/2019/03/06/settling-the-myth-of-transparent-hugepages-for-databases/
Modern machines have not only `enable` or `disable`, there is also an `madvise` setting. All my machines that I checked have the latter as default already(!) for the `enable` and `defrag` settig.
According to the definition of madvise, this disables THP by default, but allows applications to ask for THP support via an madvise() call.

I'd argue, that if mariadb and redis don't do foolishly the wrong thing, everything is fine, without any need for manual tuning.
`echo never > /sys/kernel/mm/transparent_hugepage/enabled` seems needlessly harsh to me.

**Comment by mmattel** [comment] 2020-04-09 19:55
Regarding `madvise` and redis:

quote: `...when the setting is set to madvise, applications must opt-in. redis does not opt-in...`
redis itself recommends setting THP to never, see link above.

If I set THP to `madvise` and stop/start the redis service, the well known warning gets logged:
`# WARNING you have Transparent Huge Pages (THP) support enabled in your kernel....`
Returning to `never` and stop/start redis service does not create that warning in the log.

Therefore `never` is the correct setting as documented in redis and docs.

When redis enables madvise in a proper way, this can be changed, but not for now.

**Comment by voroyam** [comment] 2021-03-09 01:51
no real progress or clear instructions on what to document where.

closing.

**Closed by voroyam** 2021-03-09 01:51 UTC
Labels: p4-low
