### ISSUE TITLE
Improve admin_manual/configuration/files/external_storage_configuration_gui.html

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#261] opened 2018-08-01 14:16 UTC
**Available Storage Backends** gives you a complete list inlcuding Local (if enabled)
But
**Allow Users to Mount External Storage** has only a list without Local

The missing Local Storage is totally fine, but it should be described that it is only avalable as sharable mount created by the admin - if this is the intention...

**At the bottom:**
...You might need to setup a cron job that runs sudo -u www-data php occ files:scan --all (or replace “–all” with the user name, see also Using the occ Command) to trigger a rescan of the user’s files periodically (for example every 15 minutes), which includes the mounted external storage.

I would add here, that recieved shared mounts are not part of a scan, for details please see the documentation of the files:scan command.

@settermjd @voroyam

**Comment by voroyam** [comment] 2019-07-29 16:10
@mmattel I added a tag to the link to the occ commands. The rest of the issue is quite fuzzy, so I did not understand what you wanted. since this is over a year old I would close this, and if it's important to you, please re open it and add additional information what you want to document where and how.

**Closed by voroyam** 2019-07-29 16:10 UTC
